# loops/inst/bluebream/zope.conf
# main zope configuration file for deployment

# Identify the component configuration used to define the site:
site-definition application.zcml

<zodb>

  <filestorage>
    path var/filestorage/Data.fs
    blob-dir var/blob
  </filestorage>

# Uncomment this if you want to connect to a ZEO server instead:
#  <zeoclient>
#    server $(ZEO_SERVER)
#    storage 1
#    # ZEO client cache, in bytes
#    cache-size $(ZEO_CACHE_SIZE)
#    # Uncomment to have a persistent disk cache
#    #client zeo1$(SERVER_ID)
#  </zeoclient>
</zodb>

<eventlog>
  # This sets up logging to both a file and to standard output (STDOUT).
  # The "path" setting can be a relative or absolute filesystem path or
  # the tokens STDOUT or STDERR.

  <logfile>
    path var/log/loops-$(SERVER_ID).log
    formatter zope.exceptions.log.Formatter
  </logfile>

  <logfile>
    path STDOUT
    formatter zope.exceptions.log.Formatter
  </logfile>
</eventlog>
